### ISSUE TITLE
Deploy docs to S3 to appear in dev.cityofchicago.org

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/open311-api-docs#2]
Build the documents in #1 and then deploy to the S3 instance hosting dev.cityofchicago.org. Specifically, placing these files in `dev.cityofchicago.org/docs/open311/`. See [this guide](https://docs.travis-ci.com/user/deployment/s3#Deploy-to-a-Specific-S3-Folder).

**Comment by tomschenkjr** [comment]
Website appears to be deploying correctly as of v1.0.1.

**Comment by geneorama** [comment]
This issue is still referenced in README.md.  Is that a mistake, or does this issue still prevent automatic deployment? (Although I'm getting other error when running `mkdocs serve`, but I have not opened an issue yet.)
